stages:
  - build
  - deploy

build-docker:
  image: ubuntu:24.04
  stage: build
  script:
    - echo "Install Docker and Git..."
    - apt-get update
    - apt-get install -yq git docker.io docker-buildx
    - echo "Fetch Dockerfile from mklatex and source environment..."
    - git submodule update --init --recursive
    - source .env
    - echo "Start building Docker image for mklatex..."
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest $MKLATEX_PATH/etc/docker/ubuntu
    - echo "Push resulting Docker image"
    - docker push $CI_REGISTRY_IMAGE:latest
    - echo "Docker image for mklatex done!"

# NOTE: Enable only if your GitLab Instance Runner allows more than 50MB artifact upload.
# build-gfx:
#   dependencies:
#     - build-docker
#   image: $CI_REGISTRY_IMAGE:latest
#   stage: build
#   script:
#     # Mitigate `ERROR: Job failed: exit code 1` without apparent error.
#     - set +o pipefail
#     - git submodule update --init --recursive
#     - source .env
#     - mklatex drawio all
#     - mklatex inkscape all
#   artifacts:
#     paths:
#       - build/gfx/drawio/*.pdf
#       - build/gfx/inkscape/*.pdf

build-latex:
  dependencies:
    - build-docker
    # - build-gfx
  image: $CI_REGISTRY_IMAGE:latest
  stage: build
  script:
    # Mitigate `ERROR: Job failed: exit code 1` without apparent error.
    - set +o pipefail
    - git submodule update --init --recursive
    - source .env
    # NOTE: Compile figures independently such that it will be parallel even on
    # Ubuntu.
    - mklatex drawio all
    - mklatex inkscape all
    - make all
  artifacts:
    paths:
      - out/*.pdf

# See:
# https://docs.gitlab.com/user/project/pages/
pages:
  dependencies:
    - build-docker
    # - build-gfx
    - build-latex
  image: $CI_REGISTRY_IMAGE:latest
  stage: deploy
  # Deploy the PDFs into the `public` directory.
  script:
    - mkdir public
    - cp -t public out/*.pdf
  artifacts:
    paths: 
      - public/
  # Deploy the PDF only for commits made to the `master` branch.
  # only: 
  #   - master
